apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    spec:      
      containers:
        - name: wordpress
          version: 18.0.0
          env: 
            - name: WORDPRESS_DB_HOST
              value: dev-wordpress-mysql          
            - name: WORDPRESS_DB_PASSWORD
              value: ""
              valueFrom: 
                secretKeyRef:
                  name: dbpassword
                  key: password